FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .
COPY test_api.py .

EXPOSE 8002

CMD ["uvicorn", "app:api", "--host", "0.0.0.0", "--port", "8002"]