sonar.projectKey=seabook-reservas
sonar.projectName=SeaBook Reservas
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/test_*.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=reportes/junit.xml
sonar.host.url=http://localhost:9000
sonar.login=***