services:
  sonarqube:
    image: sonarqube:lts-community
    container_name: seabook-sonarqube
    ports:
      - "9000:9000"
    networks:
      - seabook-net
    volumes:
      - sonarqube_data:/opt/sonarqube_data
      - sonarqube_extensions:/opt/sonarqubes/extensions
      - sonarqube_logs:/opt/sonarqube/logs 
networks: 
  seabook-net: 
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  